export enum Routes {
  Signin = 'Signin',
  Signup = 'Signup',
  VerifyOtp = 'VerifyOtp',
  AuthStack = 'AuthStack',
  HomePage = 'HomePage',
  TabNavigation = 'TabNavigation',
  SearchScreen = 'SearchScreen',
  CartScreen = 'CartScreen',
  AddressScreen = 'AddressScreen',
  ProfileTab = 'ProfileTab',
  AddressProfile = 'Address',
  Payment = 'Payment',
  MyProfile = 'My Profile',
}
